const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const db = require('../db/database');
const { UPLOADS_DIR } = require('../config/paths');
// GET /api/pdf/:brandId?fabric=Georgette&maxRate=1000&inStockOnly=true
// Uses app in_stock flag only — Tally stock is never shown externally
router.get('/:brandId', (req, res) => {
  const brand = db.prepare('SELECT * FROM brands WHERE id = ?').get(req.params.brandId);
  if (!brand) return res.status(404).json({ error: 'Brand not found' });

  const { fabric, maxRate, minRate, inStockOnly } = req.query;

  let items = db.prepare('SELECT * FROM items WHERE brand_id = ? ORDER BY name').all(brand.id);

  const itemsWithDesigns = items.map((item) => {
    let designs = db.prepare('SELECT * FROM designs WHERE item_id = ? ORDER BY CAST(design_number AS INTEGER), design_number').all(item.id);
    if (fabric) designs = designs.filter(d => d.fabric_type === fabric);
    if (maxRate) designs = designs.filter(d => d.rate <= parseFloat(maxRate));
    if (minRate) designs = designs.filter(d => d.rate >= parseFloat(minRate));
    if (inStockOnly === 'true') designs = designs.filter(d => d.in_stock !== 0);
    return { ...item, designs };
  }).filter(i => i.designs.length > 0);

  const doc = new PDFDocument({ margin: 30, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${brand.name}-catalog.pdf"`);
  doc.pipe(res);

  // Header
  doc.rect(0, 0, doc.page.width, 60).fill('#c0392b');
  doc.fillColor('white').fontSize(22).font('Helvetica-Bold').text(brand.name, 30, 18);
  if (brand.description) doc.fontSize(11).font('Helvetica').text(brand.description, 30, 43);

  const filters = [fabric, minRate && `₹${minRate}+`, maxRate && `up to ₹${maxRate}`].filter(Boolean);
  if (filters.length) {
    doc.fontSize(10).fillColor('white').text(`Filters: ${filters.join(' • ')}`, 30, brand.description ? 43 : 43, { align: 'right' });
  }

  doc.moveDown(3);

  const uploadsDir = UPLOADS_DIR;
  const colWidth = (doc.page.width - 60) / 3;
  const rowHeight = 200;

  for (const item of itemsWithDesigns) {
    // Item heading
    doc.fillColor('#c0392b').fontSize(14).font('Helvetica-Bold').text(item.name, 30, doc.y + 10);
    doc.moveTo(30, doc.y + 2).lineTo(doc.page.width - 30, doc.y + 2).strokeColor('#c0392b').stroke();
    doc.moveDown(0.5);

    let col = 0;
    let rowStartY = doc.y;

    for (const d of item.designs) {
      const x = 30 + col * colWidth;
      const y = rowStartY;

      // Photo
      const photoPath = d.photo_path ? path.join(uploadsDir, d.photo_path) : null;
      if (photoPath && fs.existsSync(photoPath)) {
        try {
          doc.image(photoPath, x, y, { width: colWidth - 8, height: 130, cover: [colWidth - 8, 130] });
        } catch { drawNoPhoto(doc, x, y, colWidth - 8, 130); }
      } else {
        drawNoPhoto(doc, x, y, colWidth - 8, 130);
      }

      // Details
      let ty = y + 133;
      doc.fillColor('#333').fontSize(10).font('Helvetica-Bold').text(`Design ${d.design_number}`, x, ty, { width: colWidth - 8 });
      ty += 13;
      doc.fillColor('#c0392b').fontSize(11).font('Helvetica-Bold').text(`₹${d.rate}`, x, ty);
      ty += 13;
      doc.fillColor('#666').fontSize(9).font('Helvetica').text(`${d.pcs_per_set} pcs/set${d.fabric_type ? ` • ${d.fabric_type}` : ''}`, x, ty, { width: colWidth - 8 });
      if (d.colors) {
        ty += 11;
        doc.fillColor('#888').fontSize(8).text(d.colors, x, ty, { width: colWidth - 8 });
      }

      col++;
      if (col === 3) {
        col = 0;
        rowStartY += rowHeight;
        if (rowStartY + rowHeight > doc.page.height - 40) {
          doc.addPage();
          rowStartY = 30;
        }
      }
    }

    if (col > 0) rowStartY += rowHeight;
    doc.y = rowStartY + 10;
    if (doc.y + rowHeight > doc.page.height - 40) { doc.addPage(); }
  }

  // Footer
  doc.fontSize(8).fillColor('#aaa').text(`Generated by Gopiram Saree • ${new Date().toLocaleDateString('en-IN')}`, 30, doc.page.height - 30, { align: 'center' });

  doc.end();
});

function drawNoPhoto(doc, x, y, w, h) {
  doc.rect(x, y, w, h).fillAndStroke('#f0ebe6', '#ddd');
  doc.fillColor('#bbb').fontSize(10).text('No Photo', x, y + h / 2 - 7, { width: w, align: 'center' });
}

module.exports = router;
